Feature task6
AlexLukashevich95/Shop pull request #9
Opened 2023-12-13 19:06 UTC by AlexLukashevich95

-added new methods for adding products to shop and show them

2023-12-21 15:59 UTC, Evgnanii requested changes

2023-12-21 15:59 UTC, Evgnanii commented on src/com/lukashevich/shop/application/Menu.java
> +        List<Product> productList = productController.getAllProducts();
добавь на бекенд метод который отдаст продукты в правильном виде по id магазина(или имени)

2023-12-21 15:59 UTC, Evgnanii commented on src/com/lukashevich/shop/application/Menu.java
> +        List<ProductShop> productShopList = shop.getProducts();
создай пустой список который будет хранить пары ключ значение. и добавляй в него id продуктов и количество. и вызывай метод бека который принимает в себя список этих пар и id магазина в который нужно добавить

2023-12-21 15:59 UTC, Evgnanii commented on src/com/lukashevich/shop/repository/impl/ShopRepositoryImpl.java
> +    public Shop addProductToShop(Shop shop) throws IOException {
такого метода не должно быть, должно быть достаточно метода saveShop. Заполнение объекта shop должно в сервисе происходить

2023-12-21 15:59 UTC, Evgnanii commented on src/com/lukashevich/shop/repository/ShopRepository.java
> +    List<ProductShop> getProductsInShop(Shop shop);
тоже самое, не должно быть этого метода. Нужные данные из магазина ты достаешь в сервисе. Репозиторий магазина не должен возвращать продукты

2023-12-21 15:59 UTC, Evgnanii commented on src/com/lukashevich/shop/repository/impl/BaseRepository.java
> +        T object = null;  //не особо понимаю , как правильно инициализировать. new Object и new T не подходят
а зачем тебе создавать этот объект? просто верни нужный объект, когда найдешь его, а не присваивай его значение новому объекту

2023-12-27 06:11 UTC, AlexLukashevich95 commented on src/com/lukashevich/shop/application/Menu.java
> +        List<ProductShop> productShopList = shop.getProducts();
Тут реализовано получение продуктов магазина в виде списка типа ProductShop. Сделано это для возможности расширения данных продуктов в магазине. К примеру можно добавить цену товара. В каждом магазине она может отличаться.

2023-12-27 06:18 UTC, AlexLukashevich95 commented on src/com/lukashevich/shop/repository/impl/BaseRepository.java
> +        T object = null;  //не особо понимаю , как правильно инициализировать. new Object и new T не подходят
не знаю как обработать возвращение значения вне условия с таким подходом. Просто возвращать null? Я помню ты говорил, что такой подход неправильный и надо избегать возвращение нула.

2024-02-04 19:28 UTC, Evgnanii approved these changes
LGTM!

2024-02-04 19:29 UTC, merged